apps:
  - name: score-service-api
    environment: production
    codebase: score-service
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 5
      targetCPUUtilizationPercentage: 80
    container:
      image:
        repository: osuakatsuki/score-service
        tag: latest
      port: 80
      readinessProbe:
        httpGet:
          path: /_health
          port: 80
        initialDelaySeconds: 10
        periodSeconds: 10
        timeoutSeconds: 3
        successThreshold: 1
        failureThreshold: 3
      resources:
        limits:
          cpu: 400m
          memory: 400Mi
        requests:
          cpu: 200m
          memory: 300Mi
      env:
        - name: APP_COMPONENT
          value: api
      imagePullSecrets:
        - name: osuakatsuki-registry-secret
    service:
      type: ClusterIP
      port: 80
